services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:8080
      - FOG_CHESS_JWT_SECRET=dev-fog
      - FOG_CHESS_JWT_AUD=fogchess
      - FOG_CHESS_JWT_ISS=main-portal
      - SESSION_SECRET=123saodh1od11283
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://fogchess:fogchess123@postgres:5432/fogchess
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fogchess
      - POSTGRES_USER=fogchess
      - POSTGRES_PASSWORD=fogchess123
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_data:
  pg_data:
