export interface AiConfig {
  materialWeight: number;
  captureWeight: number;
  kingSafetyWeight: number;
  pieceActivityWeight: number;
  centerControlWeight: number;
  mobilityWeight: number;
  threatWeight: number;
  memoryCoverageWeight: number;
  memoryDefenseWeight: number;
  memoryKingHuntWeight: number;
  beliefPoolSize: number;
  beliefSampleCount: number;
  beliefWorstCaseWeight: number;
  illegalScenarioMovePenalty: number;
  intentCriticalThreshold: number;
  responseRiskCoverageThreshold: number;
  riveTacticalWeight: number;
  riveVisionGainWeight: number;
  riveBeliefReductionWeight: number;
  riveThreatCreationWeight: number;
  riveThreatReductionWeight: number;
  riveKingSafetyWeight: number;
  rivePlanConsistencyWeight: number;
  riveWorstCaseRiskWeight: number;
  riveInformationLeakageWeight: number;
  riveOpponentResponseRiskWeight: number;
  luxNewlyVisibleWeight: number;
  luxScenariosEliminatedWeight: number;
  luxHighValueUncertaintyWeight: number;
  luxEnemyKingZoneWeight: number;
  luxThreatZoneWeight: number;
  finalHeuristicWeight: number;
  finalRiveWeight: number;
  finalLuxWeight: number;
  useStockfish: boolean;
  stockfishDepth: number;
  stockfishTimeLimitMs: number;
  maxStockfishEvaluationsPerMove: number;
  stockfishTopCandidateCount: number;
}

export const DEFAULT_AI_CONFIG: AiConfig = {
  materialWeight: 1,
  captureWeight: 10,
  kingSafetyWeight: 1,
  pieceActivityWeight: 1,
  centerControlWeight: 1,
  mobilityWeight: 1,
  threatWeight: 1,
  memoryCoverageWeight: 1,
  memoryDefenseWeight: 1,
  memoryKingHuntWeight: 1,
  beliefPoolSize: 40,
  beliefSampleCount: 24,
  beliefWorstCaseWeight: 0.25,
  illegalScenarioMovePenalty: 1600,
  intentCriticalThreshold: 0.5,
  responseRiskCoverageThreshold: 0.55,
  riveTacticalWeight: 55,
  riveVisionGainWeight: 4,
  riveBeliefReductionWeight: 16,
  riveThreatCreationWeight: 28,
  riveThreatReductionWeight: 30,
  riveKingSafetyWeight: 20,
  rivePlanConsistencyWeight: 12,
  riveWorstCaseRiskWeight: 32,
  riveInformationLeakageWeight: 15,
  riveOpponentResponseRiskWeight: 26,
  luxNewlyVisibleWeight: 0.04,
  luxScenariosEliminatedWeight: 0.35,
  luxHighValueUncertaintyWeight: 0.45,
  luxEnemyKingZoneWeight: 0.4,
  luxThreatZoneWeight: 0.35,
  finalHeuristicWeight: 1,
  finalRiveWeight: 1,
  finalLuxWeight: 35,
  useStockfish: true,
  stockfishDepth: 8,
  stockfishTimeLimitMs: 40,
  maxStockfishEvaluationsPerMove: 8,
  stockfishTopCandidateCount: 3
};
